<a href="https://colab.research.google.com/github/kotsun32/Deep_learning_practice/blob/main/00_collab_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Going over some collab/ tensor basics 

```

```



In [23]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [24]:
#create tensor with tf.constant()
#doc string command shift space 
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [25]:
#number of demensions ndim
scaler.ndim

0

In [26]:
vector = tf.constant([10,10])
vector 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [27]:
vector.ndim

1

In [28]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [29]:
matrix.ndim
#demension is total elements in shape 

2

In [30]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [31]:
changeable_variable = tf.Variable([10,7])

In [32]:
changeable_variable[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [33]:
changeable_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [34]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [35]:
tf.random.shuffle(random_1)
#randomly shuffles across first dimension so the rows in this case 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [36]:
# needs both line of code (probably) to work so random set seed and seed = in shuffle
# kinda odd but probably not only case this is true 
tf.random.set_seed(42)
tf.random.shuffle(random_1,seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [37]:
tf.ones([10,7])
#create tf of all ones 

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [38]:
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [39]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [40]:
#rank_3_tensor = rank_2_tensor[...,tf.newaxis]
#... means on every axis in stead of going [:,:,] replaces that especially usful for big tensors or maxtrixs
#newaxis will add new level to tensor


# another way to do this is tf.exapand_dims
#tf.expand_dims(rank_2, axis=-1) expands final axis 
#this also allows you to chosse where the expansion goes by changing the axis to what you want 

In [41]:
#tf has own functions for basic math that would speed up operations 
#tf.matmul for matrix multiply 
#tf.tensordot needs x or y to be transposed 
#tf.cast() for changing type 

In [42]:
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [44]:
F[42]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>